# -*- coding: utf-8 -*-
"""Titanic Funcional.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15h7VPfXC9nTRmucqn1toVqroPEY8dJYR
"""

import tensorflow as tf
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, roc_curve, auc
import numpy as np

data = pd.read_csv('./Titanic-Dataset.csv')

# Statistics numerical
data.describe()

# Statistics categorical
data.select_dtypes(include='object').describe()

# Preprocessing

# En caso de que se presenten como texto:

# data['Survived'] = data['Survived'].map({'No': 0, 'Yes': 1})
data['Sex'] = data['Sex'].map({'female': 0, 'male': 1})
#data['Pclass'] = data['Pclass'].map({'Lower': 3, 'Middle': 2, 'Upper': 1})


# Missing values
print('Missing in data:\n', data.isnull().sum())

print(data['Age'])

# Impute Age
data['Age'] = data['Age'].fillna(data['Age'].median())

# medians = data_tr.groupby(['Pclass', 'Sex'])['Age'].median()
# medians = medians.reset_index()
# age_norm_tr, age_norm_ts = [], []
# for c, s in medians[['Pclass', 'Sex']].values.tolist():
#     median = medians[(medians['Pclass'] == c) & (medians['Sex'] == s)]['Age'].values[0]
#     idx = (data_tr['Pclass'] == c) & (data_tr['Sex'] == s)
#     age_norm_tr.append(data_tr.loc[idx]['Age'].fillna(median))
#     age_norm_ts.append(data_ts.loc[idx]['Age'].fillna(median))

# data_tr['Age'] = pd.concat(age_norm_tr).sort_index()
# data_ts['Age'] = pd.concat(age_norm_ts).sort_index()

# Binning the Age and the Fare
data['Age'] = pd.cut(data['Age'], 5)
data['Fare'] = pd.qcut(data['Fare'], 5)


# Convert cabin to categorical
data['Deck'] = data['Cabin'].str[0]
data['Deck'] = data['Deck'].fillna('M')

print(data['Deck'].value_counts())

# Group Decks
data['Deck'] = data['Deck'].replace(['A', 'B', 'C'], 'ABC')
data['Deck'] = data['Deck'].replace(['D', 'E'], 'DE')
data['Deck'] = data['Deck'].replace(['F', 'G'], 'FG')

print(data['Deck'].value_counts())

# Create new column Title
data['Title'] = data['Name'].str.split(', ', expand=True)[1].str.split('.', expand=True)[0]

idx = data['Title'].value_counts() > 10
title_names = idx[idx].index.to_list()
data['Title'] = data['Title'].apply(lambda x: x if x in title_names else 'Other')


# Convert to one-hot-vectors
ohv_cols_names =  ['Embarked', 'Deck', 'Title', 'Fare', 'Age']
ohv_cols = [pd.get_dummies(data[col], prefix=col) for col in ohv_cols_names]

ohv = [ohv[:len(data)] for ohv in ohv_cols]

data = pd.concat([data] + ohv, axis=1)


# Drop
data = data.drop(['Name', 'Cabin', 'Ticket', 'PassengerId'] + ohv_cols_names, axis=1)


# Normalize numerical inputs
# for col in ['SibSp', 'Parch', 'Pclass']:
#     mean = data[col].mean()
#     std = data[col].std()
#     data[col] = (data[col] - mean) / std


for col in ['SibSp', 'Parch', 'Pclass']:
    max_ = data[col].max()
    min_ = data[col].min()
    data[col] = (data[col] - min_) / (max_ - min_)

data = data.dropna(subset=['Survived'])

data.describe()

data.select_dtypes(include='object')

# Get inputs/outputs
x = data.drop(['Survived'], axis=1).astype('float32').values
y = data['Survived'].astype('float32').values

x_tr, x_ts, y_tr, y_ts = train_test_split(x, y, test_size=0.3, random_state=42, stratify=y)

n_epochs = 500
batch_size = 128
optimizer = tf.keras.optimizers.Adam(learning_rate=0.0002)

model = tf.keras.Sequential()
model.add(tf.keras.layers.Dropout(0.2, input_shape=(x_tr.shape[1],)))
model.add(tf.keras.layers.Dense(64, activation='relu'))
model.add(tf.keras.layers.Dropout(0.2))
model.add(tf.keras.layers.Dense(32, activation='relu'))
model.add(tf.keras.layers.Dropout(0.2))
model.add(tf.keras.layers.Dense(16, activation='relu'))
model.add(tf.keras.layers.Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['Accuracy'])
hist = model.fit(x_tr,
                 y_tr,
                 shuffle=True,
                 batch_size = batch_size,
                 epochs=n_epochs,
                 validation_split=.2)

y_tr.shape

def plot_curves(history):
  plt.figure()
  plt.xlabel('Épocas')
  plt.ylabel('Error')
  plt.plot(history['loss'])
  plt.plot(history['val_loss'])
  plt.legend(['Entrenamiento', 'Validación'])

  plt.figure()
  plt.xlabel('Épocas')
  plt.ylabel('Accuracy')
  plt.plot(history['Accuracy'])
  plt.plot(history['val_Accuracy'])
  plt.legend(['Entrenamiento', 'Validación'], loc='lower right');

plot_curves(hist.history)
results = model.evaluate(x_ts, y_ts, batch_size=batch_size)
print(f"Error (Test): {results[0]}\nAccuracy (Test): {results[1]}")

probabilities = model.predict(x_ts).reshape(len(x_ts))

fpr, tpr, _ = roc_curve(y_ts, probabilities)

plt.figure()
plt.plot(fpr, tpr, label='ROC curve (area = %0.2f)' % auc(fpr, tpr))
plt.plot([0, 1], [0, 1], linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver operating characteristic example')
plt.legend(loc="lower right")
plt.show()

predictions = np.where(probabilities > .5, 1, 0)
confusion_matrix(y_true=y_ts, y_pred=predictions)