# -*- coding: utf-8 -*-
"""Miniproyecto 2: Motor inferencia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J0mKo9KsMLQqDlOo8FsB-XimDr-1mhWT
"""

# -*- coding: utf-8 -*-
import sys
# Forzar UTF-8 en la salida estándar para evitar errores de codificación en
# terminales Windows que usan cp1252 por defecto.
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

"""
Sistema Basado en Conocimiento (SBC) - CRM Bancario
=====================================================
Entregable 2: Motor de Inferencia con Razonamiento hacia Adelante

Este script implementa:
  - Forward chaining (encadenamiento hacia adelante)
  - Ciclo de inferencia completo: hechos → reglas → conclusiones
  - Trazabilidad: cadena de reglas empleada y explicación del razonamiento
  - Resolución de conflictos entre reglas

Curso de Maestría - Sistemas Basados en Conocimiento

Javier Acuña
Victor Vargas
Leonardo Zeledon

"""

# =============================================================================
# SECCIÓN 1: REPRESENTACIÓN COMPUTACIONAL DEL CONOCIMIENTO
# =============================================================================
# Frames y hechos del dominio (base de conocimiento del Entregable 1)

# -----------------------------------------------------------------------------
# 1.1 Frames (Entidades del Dominio)
# -----------------------------------------------------------------------------

class RFM:
    """Frame: Rentabilidad del cliente (sección 4.4)"""
    RECENCY_VALUES = ["Muy reciente", "Reciente", "Antiguo", "Inactivo"]
    FREQUENCY_VALUES = ["Alta", "Media", "Baja"]
    MONETARY_VALUES = ["Alta", "Media", "Baja"]
    SEGMENTOS = ["Premium activo", "Valor medio en crecimiento",
                 "Transaccional", "Riesgo de abandono", "Inactivo"]

    def __init__(self, recency: str, frequency: str, monetary: str):
        assert recency in self.RECENCY_VALUES, f"Recency inválido: {recency}"
        assert frequency in self.FREQUENCY_VALUES, f"Frequency inválido: {frequency}"
        assert monetary in self.MONETARY_VALUES, f"Monetary inválido: {monetary}"
        self.recency = recency
        self.frequency = frequency
        self.monetary = monetary
        self.segmento = None

    def __repr__(self):
        return f"RFM(R='{self.recency}', F='{self.frequency}', M='{self.monetary}', seg='{self.segmento}')"


class Servicio:
    """Frame: Servicio bancario (sección 4.2)"""
    def __init__(self, servicio_id: int, nombre: str, categoria: str):
        self.servicio_id = servicio_id
        self.nombre = nombre
        self.categoria = categoria

    def __repr__(self):
        return f"Servicio({self.servicio_id}, '{self.nombre}', '{self.categoria}')"


class ClienteServicio:
    """Frame: Relación cliente-servicio (sección 4.3)"""
    NIVELES = ["Alta", "Media", "Baja"]

    def __init__(self, servicio_id: int, activo: bool, afinidad: str,
                 tendencia_uso: str = "Media", uso_actual: str = "Media"):
        assert afinidad in self.NIVELES, f"Afinidad inválida: {afinidad}"
        self.servicio_id = servicio_id
        self.activo = activo
        self.afinidad = afinidad
        self.tendencia_uso = tendencia_uso
        self.uso_actual = uso_actual


class TipoAccionCRM:
    """Frame: Tipos de acción CRM (sección 4.5)"""
    TIPOS = {
        1: {"nombre": "Activación",   "descripcion": "Que el cliente comience a usar el producto"},
        2: {"nombre": "Crecimiento",  "descripcion": "Aumentar productos contratados o volumen"},
        3: {"nombre": "Retención",    "descripcion": "Evitar que el cliente abandone el banco"},
        4: {"nombre": "Reactivación", "descripcion": "Recuperar clientes inactivos"},
    }

    @classmethod
    def obtener(cls, tipo_id):
        return cls.TIPOS.get(tipo_id, {"nombre": "Desconocido", "descripcion": ""})


class Cliente:
    """
    Frame: Cliente (sección 4.1)
    Entidad principal que contiene todos los hechos del cliente.
    """
    ARQUETIPOS = [
        "Profesional joven digital", "Familia en expansión",
        "Cliente transaccional", "Cliente patrimonial",
        "Emprendedor o pequeño empresario"
    ]
    JOURNEY_ETAPAS = [
        "Adquisición", "Activación", "Crecimiento",
        "Madurez", "Riesgo de abandono", "Reactivación"
    ]

    def __init__(self, nombre, rfm, arquetipo, servicios=None,
                 dias_desde_apertura=120, tendencia_transacciones="Mantiene",
                 cancelacion_productos="No", saldo_promedio="Mantiene",
                 uso_tarjetas="Si", interacciones_digitales="Mantiene"):
        assert arquetipo in self.ARQUETIPOS, f"Arquetipo inválido: {arquetipo}"
        self.nombre = nombre
        self.rfm = rfm
        self.arquetipo = arquetipo
        self.servicios = servicios or []
        self.customer_journey = None
        self.canal_preferido = []
        self.nivel_rfm = None
        self.dias_desde_apertura = dias_desde_apertura
        self.tendencia_transacciones = tendencia_transacciones
        self.cancelacion_productos = cancelacion_productos
        self.saldo_promedio = saldo_promedio
        self.uso_tarjetas = uso_tarjetas
        self.interacciones_digitales = interacciones_digitales

    def afinidad(self, nombre_servicio):
        for s in self.servicios:
            srv = CATALOGO_SERVICIOS.get(s.servicio_id)
            if srv and srv.nombre.lower() == nombre_servicio.lower():
                return s.afinidad
        return "Baja"


# -----------------------------------------------------------------------------
# 1.2 Catálogo de Servicios (hechos estáticos)
# -----------------------------------------------------------------------------

CATALOGO_SERVICIOS = {
    1:  Servicio(1,  "Cuenta corriente",    "Producto transaccional"),
    2:  Servicio(2,  "Cuenta de ahorro",    "Producto transaccional"),
    3:  Servicio(3,  "Tarjeta de crédito",  "Medio de pago"),
    4:  Servicio(4,  "Tarjeta de débito",   "Medio de pago"),
    5:  Servicio(5,  "Crédito personal",    "Producto de financiamiento"),
    6:  Servicio(6,  "Crédito hipotecario", "Producto de financiamiento"),
    7:  Servicio(7,  "Crédito automotriz",  "Producto de financiamiento"),
    8:  Servicio(8,  "Fondos de inversión", "Producto de inversión"),
    9:  Servicio(9,  "Depósitos a plazo",   "Producto de inversión"),
    10: Servicio(10, "Seguros",             "Producto de protección"),
}


# -----------------------------------------------------------------------------
# 1.3 Reglas de Producción (Base de Reglas)
# -----------------------------------------------------------------------------
# Cada regla tiene: nombre, condición legible, función evaluable, consecuente

# --- Reglas de Segmentación RFM (sección 5.1.4) ---
REGLAS_RFM = [
    {"nombre": "RFM-R1", "si": "Recency=Inactivo",
     "entonces": "Segmento=Inactivo", "salience": 10,
     "evaluar": lambda r: r.recency == "Inactivo",
     "segmento": "Inactivo"},
    {"nombre": "RFM-R2", "si": "Recency=Antiguo AND Frequency=Baja",
     "entonces": "Segmento=Riesgo de abandono", "salience": 20,
     "evaluar": lambda r: r.recency == "Antiguo" and r.frequency == "Baja",
     "segmento": "Riesgo de abandono"},
    {"nombre": "RFM-R3", "si": "Frequency=Baja AND Monetary=Baja",
     "entonces": "Segmento=Transaccional", "salience": 20,
     "evaluar": lambda r: r.frequency == "Baja" and r.monetary == "Baja",
     "segmento": "Transaccional"},
    {"nombre": "RFM-R4", "si": "Recency=Muy reciente AND Frequency=Alta AND Monetary=Alta",
     "entonces": "Segmento=Premium activo", "salience": 30,
     "evaluar": lambda r: r.recency == "Muy reciente" and r.frequency == "Alta" and r.monetary == "Alta",
     "segmento": "Premium activo"},
    {"nombre": "RFM-R5", "si": "Recency=Muy reciente AND Monetary=Alta",
     "entonces": "Segmento=Valor medio en crecimiento", "salience": 20,
     "evaluar": lambda r: r.recency == "Muy reciente" and r.monetary == "Alta",
     "segmento": "Valor medio en crecimiento"},
    {"nombre": "RFM-R6", "si": "Recency=Reciente AND Monetary=Alta",
     "entonces": "Segmento=Valor medio en crecimiento", "salience": 20,
     "evaluar": lambda r: r.recency == "Reciente" and r.monetary == "Alta",
     "segmento": "Valor medio en crecimiento"},
    {"nombre": "RFM-R7", "si": "Recency=Muy reciente AND Frequency=Media",
     "entonces": "Segmento=Valor medio en crecimiento", "salience": 20,
     "evaluar": lambda r: r.recency == "Muy reciente" and r.frequency == "Media",
     "segmento": "Valor medio en crecimiento"},
    {"nombre": "RFM-R8", "si": "Recency=Reciente AND Frequency=Alta",
     "entonces": "Segmento=Valor medio en crecimiento", "salience": 20,
     "evaluar": lambda r: r.recency == "Reciente" and r.frequency == "Alta",
     "segmento": "Valor medio en crecimiento"},
    {"nombre": "RFM-R9", "si": "Recency=Antiguo AND Monetary=Baja",
     "entonces": "Segmento=Riesgo de abandono", "salience": 20,
     "evaluar": lambda r: r.recency == "Antiguo" and r.monetary == "Baja",
     "segmento": "Riesgo de abandono"},
    {"nombre": "RFM-DEFAULT", "si": "DEFAULT",
     "entonces": "Segmento=Transaccional", "salience": 0,
     "evaluar": lambda r: True,
     "segmento": "Transaccional"},
]

# Tabla de equivalencia RFM (sección 5.1.5)
EQUIVALENCIA_RFM = {
    "Premium activo": "Alto",
    "Valor medio en crecimiento": "Medio",
    "Transaccional": "Bajo",
    "Riesgo de abandono": "Bajo",
    "Inactivo": "Inactivo",
}

# --- Reglas de Customer Journey (sección 5.3.3) ---
REGLAS_JOURNEY = [
    {"nombre": "CJ-R1", "si": "Días desde apertura < 60",
     "entonces": "Etapa=Adquisición", "origen": "Explícita", "salience": 50,
     "evaluar": lambda c: c.dias_desde_apertura < 60,
     "etapa": "Adquisición"},
    {"nombre": "CJ-R2", "si": "Transacciones=Baja AND Cancelación=Si AND Tarjetas=No AND Digital=Baja",
     "entonces": "Etapa=Reactivación", "origen": "Inferida", "salience": 40,
     "evaluar": lambda c: (c.tendencia_transacciones == "Baja" and c.cancelacion_productos == "Si"
                           and c.uso_tarjetas == "No" and c.interacciones_digitales == "Baja"),
     "etapa": "Reactivación"},
    {"nombre": "CJ-R3", "si": "Transacciones=Baja AND (Cancelación=Si OR Saldo=Baja OR Digital=Baja)",
     "entonces": "Etapa=Riesgo de abandono", "origen": "Explícita", "salience": 30,
     "evaluar": lambda c: (c.tendencia_transacciones == "Baja"
                           and (c.cancelacion_productos == "Si" or c.saldo_promedio == "Baja"
                                or c.interacciones_digitales == "Baja")),
     "etapa": "Riesgo de abandono"},
    {"nombre": "CJ-R4", "si": "Días>=60 AND Tarjetas=No AND Transacciones=Baja AND Saldo=Mantiene|Baja",
     "entonces": "Etapa=Activación", "origen": "Inferida", "salience": 40,
     "evaluar": lambda c: (c.dias_desde_apertura >= 60 and c.uso_tarjetas == "No"
                           and c.tendencia_transacciones == "Baja"
                           and c.saldo_promedio in ["Mantiene", "Baja"]),
     "etapa": "Activación"},
    {"nombre": "CJ-R5", "si": "Tarjetas=Si AND Transacciones=Sube AND Saldo=Sube AND Cancelación=No",
     "entonces": "Etapa=Crecimiento", "origen": "Inferida", "salience": 40,
     "evaluar": lambda c: (c.uso_tarjetas == "Si" and c.tendencia_transacciones == "Sube"
                           and c.saldo_promedio == "Sube" and c.cancelacion_productos == "No"),
     "etapa": "Crecimiento"},
    {"nombre": "CJ-R6", "si": "Transacciones=Mantiene AND Saldo=Mantiene AND Tarjetas=Si AND Cancelación=No",
     "entonces": "Etapa=Madurez", "origen": "Inferida", "salience": 40,
     "evaluar": lambda c: (c.tendencia_transacciones == "Mantiene" and c.saldo_promedio == "Mantiene"
                           and c.uso_tarjetas == "Si" and c.cancelacion_productos == "No"),
     "etapa": "Madurez"},
    {"nombre": "CJ-DEFAULT", "si": "DEFAULT",
     "entonces": "Etapa=Madurez", "origen": "Inferida", "salience": 0,
     "evaluar": lambda c: True,
     "etapa": "Madurez"},
]

# --- Reglas de Acción CRM (sección 7.1) ---
REGLAS_ACCION = [
    {"nombre": "ACC-R1",  "si": "RFM=Alto AND Arquetipo=Patrimonial AND Journey=Crecimiento AND (Afinidad inversión=Alta OR Afinidad depósitos=Alta)",
     "entonces": "Ofrecer asesoría de inversión personalizada", "tipo_accion_id": 2, "salience": 40,
     "evaluar": lambda c: (c.nivel_rfm == "Alto" and c.arquetipo == "Cliente patrimonial"
                           and c.customer_journey == "Crecimiento"
                           and (c.afinidad("Fondos de inversión") == "Alta" or c.afinidad("Depósitos a plazo") == "Alta"))},
    {"nombre": "ACC-R2",  "si": "RFM=Medio|Alto AND Arquetipo=Joven digital AND Journey=Activación AND Afinidad TC=Alta",
     "entonces": "Campaña digital ofreciendo primera tarjeta con beneficios", "tipo_accion_id": 1, "salience": 40,
     "evaluar": lambda c: (c.nivel_rfm in ["Medio", "Alto"] and c.arquetipo == "Profesional joven digital"
                           and c.customer_journey == "Activación" and c.afinidad("Tarjeta de crédito") == "Alta")},
    {"nombre": "ACC-R3",  "si": "RFM=Alto AND Arquetipo=Familia AND Journey=Madurez AND Afinidad seguros=Alta",
     "entonces": "Ofrecer seguros familiares o seguros de vida", "tipo_accion_id": 2, "salience": 40,
     "evaluar": lambda c: (c.nivel_rfm == "Alto" and c.arquetipo == "Familia en expansión"
                           and c.customer_journey == "Madurez" and c.afinidad("Seguros") == "Alta")},
    {"nombre": "ACC-R4",  "si": "RFM=Bajo AND Arquetipo=Transaccional AND Journey=Riesgo de abandono",
     "entonces": "Campaña automática de retención con reducción de comisiones", "tipo_accion_id": 3, "salience": 30,
     "evaluar": lambda c: (c.nivel_rfm == "Bajo" and c.arquetipo == "Cliente transaccional"
                           and c.customer_journey == "Riesgo de abandono")},
    {"nombre": "ACC-R7",  "si": "RFM=Alto AND Arquetipo=Joven digital AND Journey=Crecimiento AND (Afinidad CC=Alta OR Afinidad TC=Alta)",
     "entonces": "Ofrecer productos financieros digitales avanzados (upgrade)", "tipo_accion_id": 2, "salience": 40,
     "evaluar": lambda c: (c.nivel_rfm == "Alto" and c.arquetipo == "Profesional joven digital"
                           and c.customer_journey == "Crecimiento"
                           and (c.afinidad("Cuenta corriente") == "Alta" or c.afinidad("Tarjeta de crédito") == "Alta"))},
    {"nombre": "ACC-R8",  "si": "RFM=Medio AND Arquetipo=Familia AND Journey=Crecimiento AND (Afinidad hipotecario=Alta OR Afinidad personal=Alta)",
     "entonces": "Ofrecer financiamiento (créditos de vivienda o consumo)", "tipo_accion_id": 2, "salience": 40,
     "evaluar": lambda c: (c.nivel_rfm == "Medio" and c.arquetipo == "Familia en expansión"
                           and c.customer_journey == "Crecimiento"
                           and (c.afinidad("Crédito hipotecario") == "Alta" or c.afinidad("Crédito personal") == "Alta"))},
    {"nombre": "ACC-R9",  "si": "RFM=Medio AND Arquetipo=Transaccional AND Journey=Activación AND Afinidad ahorro=Alta",
     "entonces": "Incentivar uso de cuentas con beneficios (cashback, intereses)", "tipo_accion_id": 1, "salience": 40,
     "evaluar": lambda c: (c.nivel_rfm == "Medio" and c.arquetipo == "Cliente transaccional"
                           and c.customer_journey == "Activación" and c.afinidad("Cuenta de ahorro") == "Alta")},
    {"nombre": "ACC-R10", "si": "RFM=Bajo AND Arquetipo=Joven digital AND Journey=Riesgo abandono AND Afinidad TC=Media",
     "entonces": "Campaña de reactivación digital con beneficios", "tipo_accion_id": 4, "salience": 40,
     "evaluar": lambda c: (c.nivel_rfm == "Bajo" and c.arquetipo == "Profesional joven digital"
                           and c.customer_journey == "Riesgo de abandono" and c.afinidad("Tarjeta de crédito") == "Media")},
    {"nombre": "ACC-R11", "si": "RFM=Alto AND Arquetipo=Emprendedor AND Journey=Crecimiento AND Afinidad crédito=Alta",
     "entonces": "Ofrecer líneas de crédito empresarial", "tipo_accion_id": 2, "salience": 40,
     "evaluar": lambda c: (c.nivel_rfm == "Alto" and c.arquetipo == "Emprendedor o pequeño empresario"
                           and c.customer_journey == "Crecimiento" and c.afinidad("Crédito personal") == "Alta")},
    {"nombre": "ACC-R12", "si": "RFM=Medio|Alto AND Arquetipo=Patrimonial AND Journey=Madurez AND Afinidad depósitos=Alta",
     "entonces": "Ofrecer instrumentos de inversión conservadores", "tipo_accion_id": 2, "salience": 40,
     "evaluar": lambda c: (c.nivel_rfm in ["Medio", "Alto"] and c.arquetipo == "Cliente patrimonial"
                           and c.customer_journey == "Madurez" and c.afinidad("Depósitos a plazo") == "Alta")},
    {"nombre": "ACC-R13", "si": "RFM=Bajo|Inactivo AND Segmento=Inactivo",
     "entonces": "Solo campañas automatizadas de bajo costo", "tipo_accion_id": 4, "salience": 20,
     "evaluar": lambda c: c.nivel_rfm in ["Bajo", "Inactivo"] and c.rfm.segmento == "Inactivo"},
    {"nombre": "ACC-R14", "si": "RFM=Medio AND Arquetipo=Transaccional AND Journey=Crecimiento AND Afinidad TD=Alta",
     "entonces": "Incentivar uso de medios de pago digitales", "tipo_accion_id": 2, "salience": 40,
     "evaluar": lambda c: (c.nivel_rfm == "Medio" and c.arquetipo == "Cliente transaccional"
                           and c.customer_journey == "Crecimiento" and c.afinidad("Tarjeta de débito") == "Alta")},
    {"nombre": "ACC-R6",  "si": "RFM=Alto",
     "entonces": "Priorizar campañas de retención o expansión de productos", "tipo_accion_id": 2, "salience": 10,
     "evaluar": lambda c: c.nivel_rfm == "Alto"},
]

# --- Reglas Negativas (sección 7.4) ---
# salience: 10 (1 condición c/u); todas las activadas aplican de forma acumulativa
REGLAS_NEGATIVAS = [
    {"nombre": "NEG-R1", "si": "Arquetipo=Cliente transaccional",
     "entonces": "NO ofrecer productos de inversión sofisticados", "salience": 10,
     "evaluar": lambda c: c.arquetipo == "Cliente transaccional",
     "palabras_bloqueadas": ["inversión personalizada", "instrumentos de inversión"]},
    {"nombre": "NEG-R2", "si": "Segmento RFM=Inactivo",
     "entonces": "NO ofrecer productos financieros complejos", "salience": 10,
     "evaluar": lambda c: c.rfm.segmento == "Inactivo",
     "palabras_bloqueadas": ["inversión", "crédito empresarial", "financiamiento"]},
    {"nombre": "NEG-R3", "si": "Journey=Riesgo de abandono",
     "entonces": "NO ofrecer productos nuevos complejos sin retención", "salience": 10,
     "evaluar": lambda c: c.customer_journey == "Riesgo de abandono",
     "palabras_bloqueadas": ["inversión", "upgrade", "financiamiento"]},
]

# --- Reglas de Canal (sección 7.2) ---
# salience = prioridad × 10 (arquetipo=30, journey=20, rfm=10)
REGLAS_CANAL = [
    {"nombre": "CAN-1a", "si": "Arquetipo=Profesional joven digital",       "entonces": "Digital",                       "prioridad": 3, "salience": 30, "evaluar": lambda c: c.arquetipo == "Profesional joven digital"},
    {"nombre": "CAN-1b", "si": "Arquetipo=Cliente patrimonial",             "entonces": "Asesor personal",               "prioridad": 3, "salience": 30, "evaluar": lambda c: c.arquetipo == "Cliente patrimonial"},
    {"nombre": "CAN-1c", "si": "Arquetipo=Familia en expansión",            "entonces": "Digital y asesor personal",     "prioridad": 3, "salience": 30, "evaluar": lambda c: c.arquetipo == "Familia en expansión"},
    {"nombre": "CAN-3",  "si": "Arquetipo=Emprendedor",                     "entonces": "Asesor especializado",          "prioridad": 3, "salience": 30, "evaluar": lambda c: c.arquetipo == "Emprendedor o pequeño empresario"},
    {"nombre": "CAN-4",  "si": "Arquetipo=Cliente transaccional",           "entonces": "Automatizado (digital masivo)", "prioridad": 3, "salience": 30, "evaluar": lambda c: c.arquetipo == "Cliente transaccional"},
    {"nombre": "CAN-5",  "si": "Journey=Adquisición",                       "entonces": "Digital onboarding",            "prioridad": 2, "salience": 20, "evaluar": lambda c: c.customer_journey == "Adquisición"},
    {"nombre": "CAN-6",  "si": "Journey=Crecimiento",                       "entonces": "Digital + asesor",              "prioridad": 2, "salience": 20, "evaluar": lambda c: c.customer_journey == "Crecimiento"},
    {"nombre": "CAN-7",  "si": "Journey=Madurez",                           "entonces": "Asesor personalizado",          "prioridad": 2, "salience": 20, "evaluar": lambda c: c.customer_journey == "Madurez"},
    {"nombre": "CAN-8",  "si": "Journey=Riesgo de abandono",                "entonces": "Contacto directo (llamada)",    "prioridad": 2, "salience": 20, "evaluar": lambda c: c.customer_journey == "Riesgo de abandono"},
    {"nombre": "CAN-9",  "si": "RFM=Alto",                                  "entonces": "Atención personalizada",        "prioridad": 1, "salience": 10, "evaluar": lambda c: c.nivel_rfm == "Alto"},
    {"nombre": "CAN-10", "si": "RFM=Medio",                                 "entonces": "Digital + campañas segmentadas","prioridad": 1, "salience": 10, "evaluar": lambda c: c.nivel_rfm == "Medio"},
    {"nombre": "CAN-2",  "si": "RFM=Bajo",                                  "entonces": "Automatizado bajo costo",       "prioridad": 1, "salience": 10, "evaluar": lambda c: c.nivel_rfm == "Bajo"},
]

# Prioridad por valor del cliente (resolución de conflictos)
PRIORIDAD_RFM = {"Alto": 4, "Medio": 3, "Bajo": 2, "Inactivo": 1}


# =============================================================================
# SECCIÓN 2: MOTOR DE INFERENCIA (Forward Chaining)
# =============================================================================

class MotorInferencia:
    """
    Motor de inferencia con encadenamiento hacia adelante (forward chaining).

    El ciclo de inferencia sigue estos pasos:
      1. Cargar hechos iniciales del cliente
      2. Evaluar reglas RFM → derivar hecho: segmento
      3. Aplicar equivalencia → derivar hecho: nivel_rfm
      4. Evaluar reglas Customer Journey → derivar hecho: etapa
      5. Evaluar reglas negativas → derivar hechos: restricciones
      6. Evaluar reglas de acción → generar conjunto de conflicto
      7. Resolver conflictos → seleccionar acción ganadora
      8. Evaluar reglas de canal → derivar hecho: canal preferido

    Resolución de conflictos: en cada fase se detectan todas las reglas activas
    (candidatas), se determina el criterio de desempate (salience, y en empate
    por valor RFM o por orden de definición) y se registra la decisión tomada.
    Cada paso queda registrado en la traza para explicar el razonamiento.
    """

    def __init__(self):
        self.hechos = {}              # Memoria de trabajo (hechos derivados)
        self.traza = []               # Cadena de reglas disparadas
        self.reglas_evaluadas = 0     # Contador de reglas evaluadas
        self.ciclo = 0                # Número de ciclo del motor

    def registrar_hecho(self, clave, valor, origen):
        """Agrega un hecho a la memoria de trabajo y lo registra en la traza."""
        self.hechos[clave] = valor
        self.traza.append({
            "ciclo": self.ciclo,
            "tipo": "hecho_derivado",
            "hecho": f"{clave} = {valor}",
            "origen": origen
        })

    def registrar_regla(self, regla_nombre, condicion, resultado, detalle=""):
        """Registra la activación de una regla en la traza."""
        self.traza.append({
            "ciclo": self.ciclo,
            "tipo": "regla_disparada",
            "regla": regla_nombre,
            "condicion": condicion,
            "resultado": resultado,
            "detalle": detalle
        })

    def registrar_evento(self, evento, detalle=""):
        """Registra un evento del motor en la traza."""
        self.traza.append({
            "ciclo": self.ciclo,
            "tipo": "evento",
            "evento": evento,
            "detalle": detalle
        })

    def registrar_candidatas(self, candidatas, fase):
        """Registra el conjunto de reglas candidatas detectadas en una fase."""
        self.traza.append({
            "ciclo": self.ciclo,
            "tipo": "candidatas",
            "fase": fase,
            "candidatas": [r["nombre"] for r in candidatas],
            "total": len(candidatas)
        })

    def registrar_resolucion(self, regla_elegida, criterio, n_candidatas):
        """Registra la regla elegida tras aplicar el criterio de desempate."""
        self.traza.append({
            "ciclo": self.ciclo,
            "tipo": "resolucion",
            "regla_elegida": regla_elegida["nombre"],
            "criterio": criterio,
            "n_candidatas": n_candidatas,
            "decision": regla_elegida.get("entonces", "")
        })

    # -------------------------------------------------------------------------
    # Paso 1: Cargar hechos iniciales
    # -------------------------------------------------------------------------
    def cargar_hechos_iniciales(self, cliente):
        """Carga los hechos observables del cliente en la memoria de trabajo."""
        self.ciclo = 1
        self.registrar_evento("INICIO", f"Cargando hechos del cliente: {cliente.nombre}")

        # Hechos directos (observables)
        hechos_iniciales = {
            "nombre":                   cliente.nombre,
            "recency":                  cliente.rfm.recency,
            "frequency":                cliente.rfm.frequency,
            "monetary":                 cliente.rfm.monetary,
            "arquetipo":                cliente.arquetipo,
            "dias_desde_apertura":      cliente.dias_desde_apertura,
            "tendencia_transacciones":  cliente.tendencia_transacciones,
            "cancelacion_productos":    cliente.cancelacion_productos,
            "saldo_promedio":           cliente.saldo_promedio,
            "uso_tarjetas":             cliente.uso_tarjetas,
            "interacciones_digitales":  cliente.interacciones_digitales,
        }
        for clave, valor in hechos_iniciales.items():
            self.hechos[clave] = valor

        # Afinidades
        for cs in cliente.servicios:
            srv = CATALOGO_SERVICIOS.get(cs.servicio_id)
            if srv:
                clave = f"afinidad_{srv.nombre.lower().replace(' ', '_')}"
                self.hechos[clave] = cs.afinidad

        self.registrar_evento(
            "HECHOS_CARGADOS",
            f"{len(self.hechos)} hechos iniciales en memoria de trabajo"
        )

    # -------------------------------------------------------------------------
    # Paso 2: Inferir segmento RFM
    # -------------------------------------------------------------------------
    def inferir_segmento_rfm(self, cliente):
        """
        Evalúa todas las reglas RFM, detecta candidatas y selecciona la
        de mayor salience. En empate se respeta el orden de definición.
        """
        self.ciclo = 2
        self.registrar_evento("FASE_RFM", "Evaluando reglas de segmentación RFM")

        # Recolectar todas las reglas activas (candidatas)
        candidatas = []
        for regla in REGLAS_RFM:
            self.reglas_evaluadas += 1
            if regla["evaluar"](cliente.rfm):
                candidatas.append(regla)

        self.registrar_candidatas(candidatas, "RFM")

        # Ordenar por salience desc; en empate se mantiene el orden de definición
        candidatas_ord = sorted(candidatas, key=lambda r: r["salience"], reverse=True)
        ganadora = candidatas_ord[0]

        # Determinar criterio de desempate
        max_sal = ganadora["salience"]
        empate = [r for r in candidatas_ord if r["salience"] == max_sal]
        if len(candidatas) == 1:
            criterio = "unica regla activada"
        elif len(empate) == 1:
            criterio = f"salience (mayor: {max_sal})"
        else:
            criterio = f"salience + orden_definicion (salience={max_sal})"

        self.registrar_resolucion(ganadora, criterio, len(candidatas))

        # Registrar activación y derivar hecho
        cliente.rfm.segmento = ganadora["segmento"]
        self.registrar_regla(
            ganadora["nombre"],
            ganadora["si"],
            ganadora["entonces"],
            f"Hechos usados: R={cliente.rfm.recency}, F={cliente.rfm.frequency}, M={cliente.rfm.monetary} | salience={max_sal}"
        )
        self.registrar_hecho("segmento_rfm", ganadora["segmento"], ganadora["nombre"])

        # Equivalencia (sección 5.1.5)
        nivel = EQUIVALENCIA_RFM.get(cliente.rfm.segmento, "Bajo")
        cliente.nivel_rfm = nivel
        self.registrar_hecho("nivel_rfm", nivel, f"Equivalencia: {cliente.rfm.segmento} → {nivel}")

    # -------------------------------------------------------------------------
    # Paso 3: Inferir Customer Journey
    # -------------------------------------------------------------------------
    def inferir_customer_journey(self, cliente):
        """
        Evalúa todas las reglas de Journey, detecta candidatas y selecciona la
        de mayor salience. En empate se respeta el orden de definición.
        """
        self.ciclo = 3
        self.registrar_evento("FASE_JOURNEY", "Evaluando reglas de Customer Journey")

        # Recolectar todas las reglas activas (candidatas)
        candidatas = []
        for regla in REGLAS_JOURNEY:
            self.reglas_evaluadas += 1
            if regla["evaluar"](cliente):
                candidatas.append(regla)

        self.registrar_candidatas(candidatas, "Journey")

        # Ordenar por salience desc; en empate se mantiene el orden de definición
        candidatas_ord = sorted(candidatas, key=lambda r: r["salience"], reverse=True)
        ganadora = candidatas_ord[0]

        # Determinar criterio de desempate
        max_sal = ganadora["salience"]
        empate = [r for r in candidatas_ord if r["salience"] == max_sal]
        if len(candidatas) == 1:
            criterio = "unica regla activada"
        elif len(empate) == 1:
            criterio = f"salience (mayor: {max_sal})"
        else:
            criterio = f"salience + orden_definicion (salience={max_sal})"

        self.registrar_resolucion(ganadora, criterio, len(candidatas))

        # Registrar activación y derivar hecho
        cliente.customer_journey = ganadora["etapa"]
        self.registrar_regla(
            ganadora["nombre"],
            ganadora["si"],
            ganadora["entonces"],
            f"Hechos usados: días={cliente.dias_desde_apertura}, "
            f"transacc={cliente.tendencia_transacciones}, "
            f"cancel={cliente.cancelacion_productos}, "
            f"saldo={cliente.saldo_promedio}, "
            f"tarjetas={cliente.uso_tarjetas}, "
            f"digital={cliente.interacciones_digitales} | salience={max_sal}"
        )
        self.registrar_hecho("customer_journey", ganadora["etapa"], ganadora["nombre"])

    # -------------------------------------------------------------------------
    # Paso 4: Evaluar restricciones (reglas negativas)
    # -------------------------------------------------------------------------
    def evaluar_restricciones(self, cliente):
        """
        Evalúa todas las reglas negativas y registra las restricciones activas.
        Las restricciones se aplican de forma acumulativa (no hay elección entre
        ellas): todas las activadas imponen su bloqueo.
        """
        self.ciclo = 4
        self.registrar_evento("FASE_RESTRICCIONES", "Evaluando reglas negativas")

        restricciones = []
        for regla in REGLAS_NEGATIVAS:
            self.reglas_evaluadas += 1
            if regla["evaluar"](cliente):
                restricciones.append(regla)
                self.registrar_regla(
                    regla["nombre"],
                    regla["si"],
                    regla["entonces"]
                )
                self.registrar_hecho(
                    f"restriccion_{regla['nombre']}",
                    regla["entonces"],
                    regla["nombre"]
                )

        # Registrar candidatas y criterio de acumulación
        self.registrar_candidatas(restricciones, "Restricciones")
        if restricciones:
            self.registrar_resolucion(
                {"nombre": ", ".join(r["nombre"] for r in restricciones),
                 "entonces": "Todas aplican de forma acumulativa"},
                "acumulacion (todas las activadas aplican)",
                len(restricciones)
            )
        else:
            self.registrar_evento("SIN_RESTRICCIONES", "No se activaron reglas negativas")

        return restricciones

    # -------------------------------------------------------------------------
    # Paso 5: Evaluar reglas de acción y resolver conflictos
    # -------------------------------------------------------------------------
    def inferir_accion(self, cliente, restricciones):
        """
        Evalúa reglas de acción, genera conjunto de conflicto y lo resuelve.
        Estrategia de resolución (sección Resolución de Conflictos del doc):
          1. Detectar todas las reglas activas (candidatas)
          2. Filtrar reglas bloqueadas por restricciones
          3. Ordenar por salience (mayor salience = mayor prioridad)
          4. En empate de salience, priorizar por valor del cliente (RFM)
          5. En empate, respetar orden de definición
        """
        self.ciclo = 5
        self.registrar_evento("FASE_ACCION", "Evaluando reglas de acción CRM")

        # Generar conjunto de conflicto (todas las reglas activadas)
        conjunto_conflicto = []
        for regla in REGLAS_ACCION:
            self.reglas_evaluadas += 1
            if regla["evaluar"](cliente):
                conjunto_conflicto.append(regla)
                self.registrar_regla(
                    regla["nombre"],
                    regla["si"],
                    regla["entonces"],
                    f"salience={regla['salience']}"
                )

        self.registrar_evento(
            "CONJUNTO_CONFLICTO",
            f"{len(conjunto_conflicto)} regla(s) activada(s)"
        )

        # Registrar candidatas antes del filtrado
        self.registrar_candidatas(conjunto_conflicto, "Accion")

        if not conjunto_conflicto:
            accion_default = "Comunicación informativa general según afinidad más alta"
            self.registrar_evento("ACCION_DEFAULT", accion_default)
            self.registrar_hecho("accion_crm", accion_default, "DEFAULT (ninguna regla activada)")
            return {"nombre": "DEFAULT", "entonces": accion_default, "tipo_accion_id": 1}

        # Filtrar por restricciones
        def esta_bloqueada(regla):
            for neg in restricciones:
                for palabra in neg.get("palabras_bloqueadas", []):
                    if palabra.lower() in regla["entonces"].lower():
                        return True
            return False

        reglas_validas = []
        reglas_bloqueadas = []
        for r in conjunto_conflicto:
            if esta_bloqueada(r):
                reglas_bloqueadas.append(r)
            else:
                reglas_validas.append(r)

        for rb in reglas_bloqueadas:
            self.registrar_evento(
                "REGLA_BLOQUEADA",
                f"{rb['nombre']}: '{rb['entonces']}' bloqueada por restriccion"
            )

        if not reglas_validas:
            accion_default = "Comunicación informativa general (todas bloqueadas por restricciones)"
            self.registrar_evento("TODAS_BLOQUEADAS", accion_default)
            self.registrar_hecho("accion_crm", accion_default, "DEFAULT (restricciones)")
            return {"nombre": "DEFAULT", "entonces": accion_default, "tipo_accion_id": 1}

        # Resolver conflicto: ordenar por salience desc, luego por valor RFM
        reglas_validas.sort(key=lambda r: (
            r["salience"],
            PRIORIDAD_RFM.get(cliente.nivel_rfm, 0)
        ), reverse=True)

        ganadora = reglas_validas[0]

        # Determinar criterio de desempate
        max_sal = ganadora["salience"]
        empate_sal = [r for r in reglas_validas if r["salience"] == max_sal]
        if len(reglas_validas) == 1:
            criterio = "unica regla valida tras filtrado"
        elif len(empate_sal) == 1:
            criterio = f"salience (mayor: {max_sal})"
        else:
            prio_rfm = PRIORIDAD_RFM.get(cliente.nivel_rfm, 0)
            empate_rfm = [r for r in empate_sal
                          if PRIORIDAD_RFM.get(cliente.nivel_rfm, 0) == prio_rfm]
            if len(empate_rfm) < len(empate_sal):
                criterio = f"salience + valor_rfm (salience={max_sal}, rfm={cliente.nivel_rfm})"
            else:
                criterio = f"salience + valor_rfm + orden_definicion (salience={max_sal})"

        self.registrar_resolucion(ganadora, criterio, len(reglas_validas))

        if len(reglas_validas) > 1:
            self.registrar_evento(
                "RESOLUCION_CONFLICTO",
                f"Se priorizo {ganadora['nombre']} (salience={ganadora['salience']}) "
                f"sobre {', '.join(r['nombre'] for r in reglas_validas[1:])}"
            )

        tipo = TipoAccionCRM.obtener(ganadora["tipo_accion_id"])
        self.registrar_hecho("accion_crm", ganadora["entonces"], ganadora["nombre"])
        self.registrar_hecho("tipo_accion", tipo["nombre"], ganadora["nombre"])

        return ganadora

    # -------------------------------------------------------------------------
    # Paso 6: Inferir canal preferido
    # -------------------------------------------------------------------------
    def inferir_canal(self, cliente):
        """
        Evalúa todas las reglas de canal, detecta candidatas y selecciona la
        de mayor salience. En empate se respeta el orden de definición.
        """
        self.ciclo = 6
        self.registrar_evento("FASE_CANAL", "Evaluando reglas de canal preferido")

        canales_activados = []
        for regla in REGLAS_CANAL:
            self.reglas_evaluadas += 1
            if regla["evaluar"](cliente):
                canales_activados.append(regla)
                self.registrar_regla(
                    regla["nombre"],
                    regla["si"],
                    f"Canal={regla['entonces']}",
                    f"salience={regla['salience']}"
                )

        self.registrar_candidatas(canales_activados, "Canal")

        if canales_activados:
            # Ordenar por salience desc; en empate se mantiene el orden de definición
            canales_ord = sorted(canales_activados, key=lambda r: r["salience"], reverse=True)
            principal = canales_ord[0]

            # Determinar criterio de desempate
            max_sal = principal["salience"]
            empate = [r for r in canales_ord if r["salience"] == max_sal]
            if len(canales_activados) == 1:
                criterio = "unica regla activada"
            elif len(empate) == 1:
                criterio = f"salience (mayor: {max_sal})"
            else:
                criterio = f"salience + orden_definicion (salience={max_sal})"

            self.registrar_resolucion(principal, criterio, len(canales_activados))

            cliente.canal_preferido = [r["entonces"] for r in canales_ord]
            self.registrar_hecho("canal_principal", principal["entonces"], principal["nombre"])
        else:
            self.registrar_resolucion(
                {"nombre": "DEFAULT", "entonces": "Digital (default)"},
                "ninguna regla activada", 0
            )
            cliente.canal_preferido = ["Digital (default)"]
            self.registrar_hecho("canal_principal", "Digital (default)", "DEFAULT")

    # -------------------------------------------------------------------------
    # Ejecutar ciclo completo de inferencia
    # -------------------------------------------------------------------------
    def ejecutar(self, cliente):
        """
        Ejecuta el ciclo completo de inferencia con forward chaining.
        Retorna el resultado del diagnóstico y la traza completa.
        """
        # Reset estado del motor
        self.hechos = {}
        self.traza = []
        self.reglas_evaluadas = 0
        self.ciclo = 0

        # Ciclo de inferencia
        self.cargar_hechos_iniciales(cliente)       # Ciclo 1: Hechos
        self.inferir_segmento_rfm(cliente)          # Ciclo 2: RFM → Segmento
        self.inferir_customer_journey(cliente)       # Ciclo 3: Journey → Etapa
        restricciones = self.evaluar_restricciones(cliente)  # Ciclo 4: Restricciones
        accion = self.inferir_accion(cliente, restricciones) # Ciclo 5: Acción
        self.inferir_canal(cliente)                  # Ciclo 6: Canal

        self.ciclo = 7
        self.registrar_evento("FIN", "Inferencia completada")

        return {
            "cliente": cliente.nombre,
            "hechos": dict(self.hechos),
            "accion": accion["entonces"],
            "tipo_accion": TipoAccionCRM.obtener(accion.get("tipo_accion_id", 1))["nombre"],
            "regla_aplicada": accion["nombre"],
            "canal": cliente.canal_preferido[0] if cliente.canal_preferido else "N/A",
            "traza": list(self.traza),
            "reglas_evaluadas": self.reglas_evaluadas,
        }


# =============================================================================
# SECCIÓN 3: VISUALIZACIÓN DE LA TRAZA
# =============================================================================

def imprimir_traza(resultado):
    """
    Imprime la traza completa del razonamiento del motor de inferencia.
    Muestra cada regla disparada, los hechos usados, las reglas candidatas,
    el criterio de desempate aplicado y la decisión tomada en cada fase.
    """
    print("=" * 75)
    print(f"  DIAGNOSTICO CRM: {resultado['cliente']}")
    print(f"  Reglas evaluadas: {resultado['reglas_evaluadas']}")
    print("=" * 75)

    ciclo_actual = None
    fases = {
        1: "CARGA DE HECHOS",
        2: "INFERENCIA RFM (Segmentacion)",
        3: "INFERENCIA CUSTOMER JOURNEY",
        4: "EVALUACION DE RESTRICCIONES",
        5: "INFERENCIA DE ACCION CRM",
        6: "INFERENCIA DE CANAL",
        7: "RESULTADO FINAL"
    }

    for entrada in resultado["traza"]:
        # Encabezado de fase
        if entrada["ciclo"] != ciclo_actual:
            ciclo_actual = entrada["ciclo"]
            fase = fases.get(ciclo_actual, f"CICLO {ciclo_actual}")
            print(f"\n{'-' * 75}")
            print(f"  Ciclo {ciclo_actual}: {fase}")
            print(f"{'-' * 75}")

        tipo = entrada["tipo"]

        if tipo == "evento":
            print(f"  [{entrada['evento']}] {entrada.get('detalle', '')}")

        elif tipo == "regla_disparada":
            print(f"  REGLA ACTIVADA: {entrada['regla']}")
            print(f"     SI:       {entrada['condicion']}")
            print(f"     ENTONCES: {entrada['resultado']}")
            if entrada.get("detalle"):
                print(f"     DETALLE:  {entrada['detalle']}")

        elif tipo == "candidatas":
            nombres = ", ".join(entrada["candidatas"]) if entrada["candidatas"] else "(ninguna)"
            print(f"  CANDIDATAS ({entrada['fase']}, total={entrada['total']}): {nombres}")

        elif tipo == "resolucion":
            print(f"  RESOLUCION DE CONFLICTO:")
            print(f"     Regla elegida:      {entrada['regla_elegida']}")
            print(f"     Criterio aplicado:  {entrada['criterio']}")
            print(f"     Candidatas validas: {entrada['n_candidatas']}")
            if entrada.get("decision"):
                print(f"     Decision final:    {entrada['decision']}")

        elif tipo == "hecho_derivado":
            print(f"  HECHO DERIVADO: {entrada['hecho']}")
            print(f"     ORIGEN: {entrada['origen']}")

    # Resumen final
    print(f"\n{'=' * 75}")
    print(f"  DECISION FINAL")
    print(f"{'=' * 75}")
    print(f"  Accion:  {resultado['accion']}")
    print(f"  Tipo:    {resultado['tipo_accion']}")
    print(f"  Regla:   {resultado['regla_aplicada']}")
    print(f"  Canal:   {resultado['canal']}")
    print(f"{'=' * 75}")

    # Cadena de reglas
    reglas_disparadas = [e for e in resultado["traza"] if e["tipo"] == "regla_disparada"]
    print(f"\n  CADENA DE REGLAS EMPLEADA ({len(reglas_disparadas)} reglas disparadas):")
    for i, r in enumerate(reglas_disparadas, 1):
        print(f"     {i}. [{r['regla']}] SI {r['condicion']} -> {r['resultado']}")
    print()


# =============================================================================
# SECCIÓN 4: CASOS DE PRUEBA
# =============================================================================

print("╔═══════════════════════════════════════════════════════════════════════════╗")
print("║  SISTEMA BASADO EN CONOCIMIENTO - CRM BANCARIO                         ║")
print("║  Entregable 2: Motor de Inferencia con Forward Chaining                ║")
print("╚═══════════════════════════════════════════════════════════════════════════╝")

motor = MotorInferencia()
resultados = []

# --- Caso 1: Patrimonial de alto valor en crecimiento ---
c1 = Cliente(
    nombre="Carlos Méndez",
    rfm=RFM("Muy reciente", "Alta", "Alta"),
    arquetipo="Cliente patrimonial",
    servicios=[
        ClienteServicio(1, True, "Alta"),
        ClienteServicio(8, True, "Alta"),
        ClienteServicio(9, True, "Alta"),
    ],
    dias_desde_apertura=800,
    tendencia_transacciones="Sube",
    saldo_promedio="Sube",
    uso_tarjetas="Si",
    interacciones_digitales="Sube",
)
resultados.append(motor.ejecutar(c1))
imprimir_traza(resultados[-1])

# --- Caso 2: Joven digital en activación ---
c2 = Cliente(
    nombre="María López",
    rfm=RFM("Reciente", "Media", "Alta"),
    arquetipo="Profesional joven digital",
    servicios=[
        ClienteServicio(1, True, "Media"),
        ClienteServicio(3, False, "Alta"),
        ClienteServicio(4, True, "Alta"),
    ],
    dias_desde_apertura=90,
    tendencia_transacciones="Baja",
    saldo_promedio="Mantiene",
    uso_tarjetas="No",
    interacciones_digitales="Mantiene",
)
resultados.append(motor.ejecutar(c2))
imprimir_traza(resultados[-1])

# --- Caso 3: Transaccional en riesgo de abandono ---
c3 = Cliente(
    nombre="José Ramírez",
    rfm=RFM("Antiguo", "Baja", "Baja"),
    arquetipo="Cliente transaccional",
    servicios=[
        ClienteServicio(1, True, "Media"),
        ClienteServicio(2, True, "Alta"),
        ClienteServicio(4, True, "Media"),
    ],
    dias_desde_apertura=500,
    tendencia_transacciones="Baja",
    saldo_promedio="Baja",
    uso_tarjetas="Si",
    interacciones_digitales="Baja",
)
resultados.append(motor.ejecutar(c3))
imprimir_traza(resultados[-1])

# --- Caso 4: Familia en expansión - madurez ---
c4 = Cliente(
    nombre="Ana y Pedro Solano",
    rfm=RFM("Muy reciente", "Alta", "Alta"),
    arquetipo="Familia en expansión",
    servicios=[
        ClienteServicio(1, True, "Alta"),
        ClienteServicio(3, True, "Alta"),
        ClienteServicio(6, True, "Alta"),
        ClienteServicio(10, False, "Alta"),
    ],
    dias_desde_apertura=1200,
    tendencia_transacciones="Mantiene",
    saldo_promedio="Mantiene",
    uso_tarjetas="Si",
    interacciones_digitales="Mantiene",
)
resultados.append(motor.ejecutar(c4))
imprimir_traza(resultados[-1])

# --- Caso 5: Emprendedor en crecimiento ---
c5 = Cliente(
    nombre="Roberto Chinchilla",
    rfm=RFM("Muy reciente", "Alta", "Alta"),
    arquetipo="Emprendedor o pequeño empresario",
    servicios=[
        ClienteServicio(1, True, "Alta"),
        ClienteServicio(5, True, "Alta"),
        ClienteServicio(4, True, "Alta"),
    ],
    dias_desde_apertura=400,
    tendencia_transacciones="Sube",
    saldo_promedio="Sube",
    uso_tarjetas="Si",
    interacciones_digitales="Sube",
)
resultados.append(motor.ejecutar(c5))
imprimir_traza(resultados[-1])

# --- Caso 6: Cliente nuevo (Adquisición) - DEFAULT ---
c6 = Cliente(
    nombre="Laura Jiménez",
    rfm=RFM("Muy reciente", "Baja", "Baja"),
    arquetipo="Profesional joven digital",
    servicios=[
        ClienteServicio(1, True, "Media"),
        ClienteServicio(3, False, "Alta"),
    ],
    dias_desde_apertura=15,
    tendencia_transacciones="Mantiene",
    saldo_promedio="Mantiene",
    uso_tarjetas="No",
    interacciones_digitales="Mantiene",
)
resultados.append(motor.ejecutar(c6))
imprimir_traza(resultados[-1])


# =============================================================================
# SECCIÓN 5: RESUMEN COMPARATIVO
# =============================================================================

print("\n╔═══════════════════════════════════════════════════════════════════════════╗")
print("║                       RESUMEN COMPARATIVO                              ║")
print("╚═══════════════════════════════════════════════════════════════════════════╝\n")

print(f"{'#':<4} {'Cliente':<24} {'RFM':<10} {'Journey':<22} {'Regla':<10} {'Acción':<52} {'Canal'}")
print("-" * 160)
for i, r in enumerate(resultados, 1):
    print(f"{i:<4} {r['cliente']:<24} {r['hechos'].get('nivel_rfm','?'):<10} "
          f"{r['hechos'].get('customer_journey','?'):<22} {r['regla_aplicada']:<10} "
          f"{r['accion']:<52} {r['canal']}")

print(f"\n  Total reglas evaluadas en todos los casos: "
      f"{sum(r['reglas_evaluadas'] for r in resultados)}")
print(f"  Promedio reglas evaluadas por caso: "
      f"{sum(r['reglas_evaluadas'] for r in resultados) / len(resultados):.1f}")