# -*- coding: utf-8 -*-
"""Regression Practical (Completo).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-uyusQuSDs3VbR7RmWRNDOUVa6lIziMQ
"""

import pandas as pd
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# 1. Cargar el dataset público
print("Cargando el dataset de California Housing...")
california = fetch_california_housing()
X = pd.DataFrame(california.data, columns=california.feature_names)
y = california.target # El valor mediano de las casas (en cientos de miles de dólares)

# 2. Dividir los datos en Entrenamiento (80%) y Prueba (20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# ==========================================
# MODELO 1: Regresión Lineal
# ==========================================
print("\nEntrenando modelo de Regresión Lineal...")
lr_model = LinearRegression()
lr_model.fit(X_train, y_train)

# Hacer predicciones
lr_predictions = lr_model.predict(X_test)

# Evaluar Regresión Lineal
lr_mse = mean_squared_error(y_test, lr_predictions)
lr_mae = mean_absolute_error(y_test, lr_predictions)
lr_r2 = r2_score(y_test, lr_predictions)

# ==========================================
# MODELO 2: Random Forest Regressor
# ==========================================
print("Entrenando modelo de Random Forest (esto puede tomar unos segundos)...")
# Usamos 100 árboles (n_estimators=100)
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

# Hacer predicciones
rf_predictions = rf_model.predict(X_test)

# Evaluar Random Forest
rf_mse = mean_squared_error(y_test, rf_predictions)
rf_mae = mean_absolute_error(y_test, rf_predictions)
rf_r2 = r2_score(y_test, rf_predictions)

# ==========================================
# RESULTADOS
# ==========================================
print("\n--- COMPARACIÓN DE RENDIMIENTO ---")
print(f"Regresión Lineal:")
print(f"  MSE: {lr_mse:.4f}")
print(f"  MAE: {lr_mae:.4f}")
print(f"  R2:  {lr_r2:.4f}")

print(f"\nRandom Forest Regressor:")
print(f"  MSE: {rf_mse:.4f}")
print(f"  MAE: {rf_mae:.4f}")
print(f"  R2:  {rf_r2:.4f}")

print("\n--- PESOS DE LA REGRESIÓN LINEAL ---")
print(f"Intersección (Bias/b): {lr_model.intercept_:.4f}")

# Emparejamos cada peso con el nombre de su columna original
pesos_lr = pd.DataFrame({
    'Variable': X.columns,
    'Peso (Coeficiente)': lr_model.coef_
})

# Ordenamos por el valor absoluto del peso para ver los más impactantes primero
pesos_lr['Impacto Absoluto'] = pesos_lr['Peso (Coeficiente)'].abs()
pesos_lr = pesos_lr.sort_values(by='Impacto Absoluto', ascending=False)
print(pesos_lr[['Variable', 'Peso (Coeficiente)']])

print("\n--- IMPORTANCIA DE VARIABLES (RANDOM FOREST) ---")

importancias_rf = pd.DataFrame({
    'Variable': X.columns,
    'Importancia': rf_model.feature_importances_
})

# Ordenamos de mayor a menor importancia
importancias_rf = importancias_rf.sort_values(by='Importancia', ascending=False)

# Las importancias en sklearn siempre suman 1.0 (100%)
importancias_rf['Importancia (%)'] = importancias_rf['Importancia'] * 100
print(importancias_rf[['Variable', 'Importancia (%)']])

!pip install skl2onnx onnxruntime

import numpy as np
from skl2onnx import to_onnx

print("Exportando el modelo Random Forest a ONNX...")

# Convertimos explícitamente una muestra de nuestros datos a float32 (numpy)
# Esto le sirve a to_onnx como "plantilla" para saber qué tipo de entradas esperar.
X_sample = X_train[:1].values.astype(np.float32)

# Convertir el modelo
# Le pasamos el modelo entrenado y la plantilla de entrada
onnx_model = to_onnx(rf_model, X_sample)

# Guardar el modelo en el disco
archivo_onnx = "modelo_rf_california.onnx"
with open(archivo_onnx, "wb") as f:
    f.write(onnx_model.SerializeToString())

print(f"¡Modelo guardado exitosamente como '{archivo_onnx}'!")

import onnxruntime as rt

print("\nCargando el modelo ONNX para inferencia...")

# 1. Iniciar la sesión de inferencia cargando el archivo físico
session = rt.InferenceSession("modelo_rf_california.onnx", providers=["CPUExecutionProvider"])

# 2. ONNX asigna nombres internos a sus "nodos" de entrada y salida.
# Extraemos cómo se llama el puerto de entrada que espera nuestros datos.
input_name = session.get_inputs()[0].name
output_name = session.get_outputs()[0].name

print(f"Nombre del input esperado: {input_name}")

# 3. Preparar los datos de prueba
# IMPORTANTE: onnxruntime no entiende de Pandas DataFrames.
# Exige matrices crudas de Numpy en el tipo de dato exacto (float32).
X_test_numpy = X_test.values.astype(np.float32)

# 4. Ejecutar la predicción
# El formato es session.run([lista_de_salidas], {diccionario_de_entradas})
predicciones_onnx = session.run([output_name], {input_name: X_test_numpy})[0]

# Comprobación rápida para ver si funciona
print("\nPrimeras 5 predicciones usando ONNXRuntime:")
print(predicciones_onnx[:5].flatten())